#!/bin/bash
# Copyright 2023 NXP                                                                                                              
# SPDX-License-Identifier: BSD-3-Clause

echo "running" $0
echo "param1: " $1
